# Generated by Django 5.2.12 on 2026-03-19 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLoginAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('password', models.CharField(help_text='Stored hashed (set via Password field in admin).', max_length=256)),
                ('api_token', models.CharField(blank=True, db_index=True, editable=False, max_length=64, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App login account',
                'verbose_name_plural': 'App login accounts',
                'ordering': ('-created_at',),
            },
        ),
    ]
